sonar.projectKey=ctse-assignment
sonar.projectName=ctse-assignment
sonar.projectVersion=1.0

sonar.sources=api-gateway,frontend,services
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**,**/.vite/**